export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_DEFAULT_PLAYLIST: "SET_DEFAULT_PLAYLISTS", // 우리가 최초에 설정한 6 가지 PLY
};

export default {
  CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
  CLIENT_SECRET: process.env.REACT_APP_CLIENT_SCRET,
  REDIRECT_URI: process.env.REACT_APP_REDIRECT_URI,
  PLAYER_ID: process.env.REACT_APP_PLAYER_ID,
  ENDPOINT_URI: "http://localhost:8080", //7d15-125-248-25-49.jp.ngrok.io",
  LIGHT1: "0b4a112c-feb0-4457-afba-3c859b9f70ad",
  LIGHT2: "a800f06f-f1aa-4014-8b21-9b72ec129062",
};
